services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: todo_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: todo_user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todo_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Laravel Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: todo_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: todo_app
      DB_USERNAME: todo_user
      DB_PASSWORD: secret

  # Angular Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: todo_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - todo_network
    environment:
      - NODE_ENV=development

networks:
  todo_network:
    driver: bridge

volumes:
  db_data:
    driver: local
